#!/bin/bash

if [ -z $SUDO_USER ]; then
  echo "Please run the script using sudo, e.g.,"
  echo ""
  echo "sudo ./build_mysql"
  exit 1
fi

# Start with MariaDB server.
sudo yum install -y mariadb-server mariadb

#install expect (needed later)
sudo yum install -y expect

#mv /opt/local/etc/mysql55/my.cnf /opt/local/etc/mysql55/my.cnf.disabled
#echo "Disabled my.cnf in /optlocal/etc/mysql55/my.cnf; please use /etc/my.cnf"

# Start MySQL.
sudo systemctl enable mariadb.service
sudo systemctl start mariadb.service

# Need enough time for tablespace creation or expect will not connect.
echo "Waiting 30 seconds for tablespace creation"
sleep 30

echo ""
echo "If the following fails, you will need to run mysql_secure_installation"
echo "by hand after the script completes."
echo ""

# Expect is not always working as, heh heh, expected. If 
# mysql_secure_installation fails, it can be run after the script completes.
# A heredoc for expect that automatically answers the questions.
expect -- << EOF
sudo spawn mysql_secure_installation
expect "Enter current password for root (enter for none):"
send "\r"
	
expect "Set root password?"
send "y\r"

expect "New password:"
send "password\r"

expect "Re-enter new password:"
send "password\r"

expect "Remove anonymous users?"
send "y\r"

expect "Disallow root login remotely?"
send "y\r"

expect "Remove test database and access to it?"
send "y\r"

expect "Reload privilege tables now?"
send "y\r"
EOF

echo
echo "MariaDB-server and client should now be installed."
echo
