#!/bin/bash

if [ -z $SUDO_USER ]; then
  echo "Please run the script using sudo, e.g.,"
  echo ""
  echo "sudo ./build_lamp"
  exit 1
fi

# Install apache2 and friends.
yum install -y php httpd php-gd php-ldap php-mbstring php-mcrypt php-mysql php-pear
echo "date.timezone = 'America/Chicago'" >> /etc/php.ini
echo "error_log = /var/log/php.log" >> /etc/php.ini

# PHP will log errors to /var/log/php.log.
touch /var/log/php.log
sudo chown apache:apache /var/log/php.log
#selinux context needs set to let apache write to the log
sudo semanage fcontext -a -t httpd_log_t "/var/log/php.log"
sudo restorecon -R -v /var/log/php.log

#backup running httpd config
cp /etc/httpd/conf/httpd.conf /etc/httpd/conf/httpd.conf.bak
mkdir /etc/httpd/sites-available
mkdir /etc/httpd/sites-enabled

# Websites will live in ~/Sites.
mkdir -p ~/Sites
#chown -R $SUDO_USER ~/Sites

FQHN=$(hostname)
echo "127.0.0.1 local.dev" >> /etc/hosts

echo "IncludeOptional sites-enabled/*.conf" >> /etc/httpd/conf/httpd.conf

echo "<VirtualHost *:80>" >> /etc/httpd/sites-available/local.dev.conf
echo "    ServerName local.dev" >> /etc/httpd/sites-available/local.dev.conf
echo "    DocumentRoot "$HOME/Sites"" >> /etc/httpd/sites-available/local.dev.conf
echo "    <Directory "$HOME/Sites">" >> /etc/httpd/sites-available/local.dev.conf
echo "      Options Indexes FollowSymLinks" >> /etc/httpd/sites-available/local.dev.conf
echo "      DirectoryIndex index.php index.html" >> /etc/httpd/sites-available/local.dev.conf
echo "      Order deny,allow" >> /etc/httpd/sites-available/local.dev.conf
echo "      Require local" >> /etc/httpd/sites-available/local.dev.conf
echo "      Deny from all" >> /etc/httpd/sites-available/local.dev.conf
echo "      AllowOverride All" >> /etc/httpd/sites-available/local.dev.conf
echo "    </Directory>" >> /etc/httpd/sites-available/local.dev.conf
echo "</VirtualHost>" >> /etc/httpd/sites-available/local.dev.conf

#setup selinux context for Sites & drupal files folders
#seems it needs to write in css & js folders (caching I assume)
sudo semanage fcontext -a -t httpd_sys_rw_content_t "/home/$USER/Sites(/.*)?"
sudo restorecon -R -v /home/$USER/Sites
sudo semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/drupal_tmp(/.*)?"
sudo restorecon -R -v /var/www/drupal_tmp
sudo semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/drupal_private(/.*)?"
sudo restorecon -R -v /var/www/drupal_private
#currently throwing SELinux alerts for httpd not being able to use port 8983 (solr)


# Start Apache
systemctl enable httpd.service
ssytemctl start httpd.service

echo 'te() { sudo tail -f /var/log/httpd/error_log; }' >> ~/.bash_profile
echo 'ta() { sudo tail -f /var/log/httpd/access_log; }' >> ~/.bash_profile
echo 'tp() { sudo tail -f /var/log/php.log; }' >> ~/.bash_profile
echo "alias acr='sudo systemctl restart httpd'" >> ~/.bash_profile
echo
echo "MySQL was not installed. To install, run separate script build_mysql."
echo "Complete. Open a new Terminal window for profile settings to take effect."
echo
