#!/bin/bash

# Start with MariaDB server.
yum install -y mariadb-server mariadb

#mv /opt/local/etc/mysql55/my.cnf /opt/local/etc/mysql55/my.cnf.disabled
#echo "Disabled my.cnf in /optlocal/etc/mysql55/my.cnf; please use /etc/my.cnf"

# Start MySQL.
systemctl enable mariadb.service
systemctl start mariadb.service

# Need enough time for tablespace creation or expect will not connect.
echo "Waiting 30 seconds for tablespace creation"
sleep 30

echo ""
echo "If the following fails, you will need to run mysql_secure_installation"
echo "by hand after the script completes."
echo ""

# Expect is not always working as, heh heh, expected. If 
# mysql_secure_installation fails, it can be run after the script completes.
# A heredoc for expect that automatically answers the questions.
expect -- << EOF
spawn mysql_secure_installation
expect "Enter current password for root (enter for none):"
send "\r"
	
expect "Set root password?"
send "y\r"

expect "New password:"
send "password\r"

expect "Re-enter new password:"
send "password\r"

expect "Remove anonymous users?"
send "y\r"

expect "Disallow root login remotely?"
send "y\r"

expect "Remove test database and access to it?"
send "y\r"

expect "Reload privilege tables now?"
send "y\r"
EOF

echo
echo "MariaDB-server and client should now be installed."
echo
echo "If you want it to start at startup, type:"
echo "sudo launchctl load -w /Library/LaunchDaemons/org.macports.mysql55-server.plist"
echo
echo "If you cannot get into MySQL you can reset the root password by"
echo "starting it manually:"
echo
echo "sudo -u _mysql /opt/local/lib/mysql55/bin/mysqld --user=_mysql --skip-grant-tables"
echo
echo "Then type mysql at the command line and set the root password:"
echo
echo "USE mysql;"
echo "UPDATE user SET password=PASSWORD('foo') WHERE User='root';"
echo "FLUSH PRIVILEGES;"
echo
