#!/bin/bash

#this script installs drush 5.9 to be compatible with luggage

#download drush
curl https://codeload.github.com/drush-ops/drush/tar.gz/5.9.0 -o drush-5.9.0.tar.gz

gunzip drush-5.9.0.tar.gz
tar -xvf drush-5.9.0.tar.gz

mv drush-5.9.0 /home/$USER/drush-5.9.0

chmod u+x /home/$USER/drush-5.9.0/drush

ln -s /home/$USER/drush-5.9.0/drush /usr/bin/drush
